//using (FileStream fs = new FileStream("Themes.dat", FileMode.OpenOrCreate))
//{
//    formatter.Serialize(fs, new Theme[10] {
//                new Theme(new byte[] { 57, 62, 70 },
//                          new byte[] { 0, 146, 202 },
//                          new byte[] { 238, 238, 238 },
//                          new byte[] { 77, 82, 90 },
//                          "Resourses/Themes/DarkBlue.png"),
//                new Theme(new byte[] { 211,214,219 },
//                          new byte[] { 190,49,68 },
//                          new byte[] { 58,71,80 },
//                          new byte[] { 191,194,199 },
//                          "Resourses/Themes/LightRed.png"),
//                new Theme(new byte[] { 62, 54, 54 },
//                          new byte[] { 215, 35, 35 },
//                          new byte[] { 245, 237, 237 },
//                          new byte[] { 82, 74, 74 },
//                          "Resourses/Themes/DarkRed.png"),
//                new Theme(new byte[] { 57,62,70 },
//                          new byte[] { 118,234,215 },
//                          new byte[] { 238, 238, 238 },
//                          new byte[] { 77, 82, 90 },
//                          "Resourses/Themes/DarkTurquoise.png"),
//                new Theme(new byte[] { 57, 62, 70 },
//                          new byte[] { 214, 90,  49 },
//                          new byte[] { 238, 238, 238 },
//                          new byte[] { 77, 82, 90 },
//                          "Resourses/Themes/DarkOrange.png"),
//                new Theme(new byte[] { 238,238,238 },
//                          new byte[] { 27,108,168 },
//                          new byte[] { 57,62,70 },
//                          new byte[] { 218,218,218 },
//                          "Resourses/Themes/LightBlue.png"),
//                new Theme(new byte[] { 58, 71, 80 },
//                          new byte[] { 246, 201, 14 },
//                          new byte[] { 238, 238, 238 },
//                          new byte[] { 78, 91, 100 },
//                          "Resourses/Themes/DarkYellow.png"),
//                new Theme(new byte[] { 237,244,242 },
//                          new byte[] { 0,144,158 },
//                          new byte[] { 63,63,68 },
//                          new byte[] { 217,224,222 },
//                          "Resourses/Themes/LighterBlue.png"),
//                new Theme(new byte[] { 57,62,70 },
//                          new byte[] { 196,251,109 },
//                          new byte[] { 238,238,238 },
//                          new byte[] { 77,82,90 },
//                          "Resourses/Themes/DarkGreen.png"),
//                new Theme(new byte[] { 242,244,247 },
//                          new byte[] { 228,58,25 },
//                          new byte[] { 2,2,5 },
//                          new byte[] { 222,224,227 },
//                          "Resourses/Themes/LightOrange.png")});
//}